# Generated by Django 4.2.6 on 2023-10-23 03:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=225)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=225)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('Domant', 'Domant'), ('Onboarding', 'Onboarding'), ('Processing', 'Processing'), ('Active', 'Active'), ('Available', 'Available'), ('Engaged', 'Engaged'), ('Withdraw', 'Withdraw'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted'), ('Archive', 'Archive')], default='Onboarding', max_length=225)),
                ('national_id', models.CharField(max_length=225)),
                ('national_id_document', models.FileField(upload_to='')),
                ('driving_licence', models.FileField(upload_to='')),
                ('good_conduct', models.FileField(upload_to='')),
                ('kra_pin', models.FileField(upload_to='')),
                ('defensive_driving_certificate', models.FileField(upload_to='')),
                ('reference_letter_from_chief', models.FileField(upload_to='')),
                ('profile_photo', models.ImageField(upload_to='profilePhotos')),
                ('medical_report', models.FileField(upload_to='')),
                ('appointment_letter', models.FileField(upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_or_person', models.CharField(choices=[('Business', 'Business'), ('Individual', 'Individual')], default='Business', max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=225)),
                ('insurance_certificate_number', models.CharField(max_length=225)),
                ('vehicle_photo', models.ImageField(upload_to='', verbose_name='vehicleProfiles')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('Vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodaapp.vehicletype')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodaapp.carrier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('Motorcyle', 'Motorcycle'), ('TukTuk', 'TukTuk')], default='Motorcyle', max_length=225)),
                ('pickup_location', models.CharField(max_length=225)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_location', models.CharField(max_length=225)),
                ('dropoff_contact_name', models.CharField(max_length=225)),
                ('dropoff_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dropoff_instruction', models.TextField()),
                ('order_status', models.CharField(choices=[('Inprogress', 'Inprogress'), ('Upcoming', 'Upcoming'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], max_length=225)),
                ('payment_status', models.CharField(max_length=225)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodaapp.shipper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=225)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('job_title', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
