# Generated by Django 4.2.6 on 2023-10-18 00:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bodaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_or_person', models.CharField(choices=[('Business', 'Business'), ('Individual', 'Individual')], default='Business', max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
