# Generated by Django 4.2.6 on 2023-10-18 01:25

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bodaapp', '0002_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=225)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=225)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('city', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('Domant', 'Domant'), ('Onboarding', 'Onboarding'), ('Processing', 'Processing'), ('Active', 'Active'), ('Available', 'Available'), ('Engaged', 'Engaged'), ('Withdraw', 'Withdraw'), ('Suspended', 'Suspended'), ('Blacklisted', 'Blacklisted'), ('Archive', 'Archive')], default='Onboarding', max_length=225)),
                ('national_id', models.CharField(max_length=225)),
                ('national_id_document', models.FileField(upload_to='')),
                ('driving_licence', models.FileField(upload_to='')),
                ('good_conduct', models.FileField(upload_to='')),
                ('kra_pin', models.FileField(upload_to='')),
                ('defensive_driving_certificate', models.FileField(upload_to='')),
                ('reference_letter_from_chief', models.FileField(upload_to='')),
                ('profile_photo', models.ImageField(upload_to='profilePhotos')),
                ('medical_report', models.FileField(upload_to='')),
                ('appointment_letter', models.FileField(upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shipper',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='email',
            field=models.EmailField(max_length=225),
        ),
    ]
