# Generated by Django 4.2.6 on 2023-10-19 02:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bodaapp', '0006_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('Motorcyle', 'Motorcycle'), ('TukTuk', 'TukTuk')], default='Motorcyle', max_length=225)),
                ('pickup_location', models.CharField(max_length=225)),
                ('pickup_date', models.DateTimeField()),
                ('dropoff_location', models.CharField(max_length=225)),
                ('dropoff_contact_name', models.CharField(max_length=225)),
                ('dropoff_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dropoff_instruction', models.TextField()),
                ('order_status', models.CharField(choices=[('Inprogress', 'Inprogress'), ('Upcoming', 'Upcoming'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], max_length=225)),
                ('payment_status', models.CharField(max_length=225)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodaapp.shipper')),
            ],
        ),
    ]
